#!/usr/bin/env bash
# Regenerates src/ltc_namespace.h from the global symbols of the cgo translation unit
# built by secp256k1.go. Rerun after updating the C sources.
set -euo pipefail

cd "$(dirname "$0")"

tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT

cat > "$tmp_dir/tu.c" <<'TU'
#define USE_BASIC_CONFIG
#define ENABLE_MODULE_GENERATOR
#define ENABLE_MODULE_BULLETPROOF
#include <string.h>
#include "basic-config.h"
#include "secp256k1.c"
#include "precomputed_ecmult.c"
#include "precomputed_ecmult_gen.c"
TU

"${CC:-gcc}" -c -O2 -Isrc -I. -Iinclude "$tmp_dir/tu.c" -o "$tmp_dir/tu.o"

{
	echo '// Code generated by gen_namespace.sh. DO NOT EDIT.'
	echo '// NOTE: Prefix every global symbol so this copy of libsecp256k1 can be linked'
	echo '// into one binary with other copies (e.g. go-ethereum/crypto/secp256k1).'
	echo '#ifndef LTC_SECP256K1_NAMESPACE_H'
	echo '#define LTC_SECP256K1_NAMESPACE_H'
	nm -g --defined-only "$tmp_dir/tu.o" | awk '{print $3}' | LC_ALL=C sort | awk '{printf "#define %s ltc_%s\n", $1, $1}'
	echo '#endif'
} > src/ltc_namespace.h
